Practice Problem 1: Create a 4×4 random matrix and check if it is symmetric.

In [1]:
import numpy as np

# Generate a 4x4 random matrix
random_matrix = np.random.randint(1, 10, (4, 4))

# Check if the matrix is symmetric
is_symmetric = (random_matrix == random_matrix.T).all()

# Output the matrix and its symmetry status
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric?", is_symmetric)


Random Matrix:
 [[7 2 5 5]
 [1 4 6 7]
 [7 3 4 8]
 [1 8 9 3]]

Is the random matrix symmetric? False


Practice Problem 2: Find the trace of a 5×5 identity matrix.

In [2]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Calculate the trace
trace = np.trace(identity_matrix)

# Output the matrix and the trace
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nTrace of the 5x5 Identity Matrix:", trace)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of the 5x5 Identity Matrix: 5.0


Practice Problem 3: Compute the determinant of a 3×3 matrix using NumPy.

In [3]:
# Define a 3x3 matrix
matrix_3x3 = np.array([[2, 3, 1], [4, 5, 6], [7, 8, 9]])

# Calculate the determinant
determinant = np.linalg.det(matrix_3x3)

# Output the matrix and its determinant
print("3x3 Matrix:\n", matrix_3x3)
print("\nDeterminant of the 3x3 Matrix:", determinant)


3x3 Matrix:
 [[2 3 1]
 [4 5 6]
 [7 8 9]]

Determinant of the 3x3 Matrix: 9.000000000000005


Practice Problem 4: Generate a random 3×3 matrix and find its transpose and determinant

In [4]:
# Generate a random 3x3 matrix
pixel_matrix = np.random.randint(0, 256, (3, 3))

# Calculate the transpose
transpose = pixel_matrix.T

# Calculate the determinant
determinant = np.linalg.det(pixel_matrix)

# Output the matrix, its transpose, and its determinant
print("Random 3x3 Matrix:\n", pixel_matrix)
print("\nTranspose of the Matrix:\n", transpose)
print("\nDeterminant of the Matrix:", determinant)


Random 3x3 Matrix:
 [[ 66  39  37]
 [178 185 212]
 [ 13 183 240]]

Transpose of the Matrix:
 [[ 66 178  13]
 [ 39 185 183]
 [ 37 212 240]]

Determinant of the Matrix: -72478.99999999981


Practice Problem 5: Create a symmetric 3×3 matrix and verify its properties.

In [5]:
# Define a symmetric 3x3 matrix
symmetric_matrix = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])

# Check if the matrix is symmetric
is_symmetric = (symmetric_matrix == symmetric_matrix.T).all()

# Output the matrix and its symmetry status
print("Symmetric 3x3 Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric?", is_symmetric)


Symmetric 3x3 Matrix:
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

Is the matrix symmetric? True


Bonus Challenge: Write a function that checks if an
nxn
nxn matrix is invertible. If it is, return its inverse; otherwise, print that the matrix is not invertible.

In [6]:
import numpy as np

def check_invertible(matrix):
    """
    Function to check if a matrix is invertible.
    If invertible, returns the inverse.
    Otherwise, prints a message that the matrix is not invertible.
    """
    # Calculate the determinant
    determinant = np.linalg.det(matrix)
    print(f"Determinant of the matrix: {determinant}")

    # Check if the determinant is non-zero
    if determinant != 0:
        inverse_matrix = np.linalg.inv(matrix)
        print("The matrix is invertible. Its inverse is:")
        return inverse_matrix
    else:
        print("The matrix is not invertible.")
        return None

# Example usage:
# Define an example matrix
example_matrix = np.array([[4, 7, 2], [3, 6, 1], [2, 5, 8]])

# Check if the matrix is invertible
result = check_invertible(example_matrix)

# Print the result
if result is not None:
    print(result)


Determinant of the matrix: 23.999999999999993
The matrix is invertible. Its inverse is:
[[ 1.79166667 -1.91666667 -0.20833333]
 [-0.91666667  1.16666667  0.08333333]
 [ 0.125      -0.25        0.125     ]]
